version: '3'
services:
  xdummy:
    build:
      context: docker
      dockerfile: Dockerfile.Xdummy
    container_name: xdummy
    volumes:
      - X11:/tmp/.X11-unix
    restart: always
  torcs:
    build:
      context: docker
      dockerfile: Dockerfile.torcs
      args:
        DISPLAY_WIDTH: 480
        DISPLAY_HEIGHT: 360
    container_name: torcs
    ports:
      - 3101:3101  # torcs
      - 5901:5901  # vnc
      - 6901:6901  # web vnc
    restart: always
    environment:
      VNC_PW: tftorcs
    privileged: True
  tensorflow:
    build:
      context: docker
      dockerfile: Dockerfile # .tf
    container_name: tensorflow
    depends_on:
      - xdummy
    links:
      - torcs
    environment:
      DISPLAY: :1
      TORCS_HOST: torcs
      TORCS_PORT: 3101
    command: python3 ${TARGET:-run.py}  # tail -f /dev/null
    working_dir: /wd
    ports:
      - 8888:8888
    volumes:
      - X11:/tmp/.X11-unix
      - ${WD:-/home/ubuntu}:/wd
  tensorboard:
    image: tensorflow/tensorflow:1.2.1-py3
    container_name: tensorboard
    command: tensorboard --logdir /wd --port 6006
    restart: always
    working_dir: /wd
    volumes:
      - ${WD:-/home/ubuntu}/logs:/wd
    ports:
      - 6006:6006
volumes:
  X11:
