version: '3'
services:
  xdummy:
    build:
      context: docker
      dockerfile: Dockerfile.Xdummy
    container_name: xdummy
    volumes:
      - X11:/tmp/.X11-unix
    restart: always
  tensorflow:
    build:
      context: docker
      dockerfile: Dockerfile.tf
    container_name: tensorflow
    depends_on:
      - xdummy
    environment:
      DISPLAY: :1
    command: python3 run.py
    working_dir: /wd
    ports:
      - 8888:8888
    volumes:
      - X11:/tmp/.X11-unix
      - /home/ubuntu:/wd
  tensorboard:
    image: tensorflow/tensorflow:1.2.1-py3
    container_name: tensorboard
    command: tensorboard --logdir /wd --port 6006
    restart: always
    working_dir: /wd
    volumes:
      - /home/ubuntu:/wd
    ports:
      - 6006:6006
volumes:
  X11:
